version: '3.9'

services:

  mysql-kc:
    image: mysql:8.0.27
    ports:
      - "3366:3306"
    restart: unless-stopped
    environment:
      MYSQL_USER: ${KEYCLOAK_USER}
      MYSQL_PASSWORD: ${KEYCLOAK_PASSWORD}
      MYSQL_DATABASE: ${KEYCLOAK_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak-w:
    image: jboss/keycloak
    ports:
      - ${KEYCLOAK_PORT}:8080
    restart: unless-stopped
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: mysql
      DB_ADDR: mysql-kc
      DB_PORT: 3306
      DB_USER: ${KEYCLOAK_USER}
      DB_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_DATABASE: ${KEYCLOAK_DB}
    depends_on:
      - mysql-kc
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume: