spring:
  security:
    oauth2:
      client:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8191/auth/realms/spring-auth
          jwk-set-uri: http://localhost:8191/auth/realms/spring-auth/protocol/openid-connect/certs
  application:
    name: auth-server

